name: Build EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller pyautogui

      - name: Build installer executable
        run: pyinstaller --onefile --noconfirm installer.py

      - name: Build OOBE executable
        run: pyinstaller --onefile --noconfirm OOBE.py

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: executables
          path: |
            dist/installer.exe
            dist/OOBE.exe

